myblog/blog/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('blog.views',
	url(r'^post/(?P<pk>\d+)/$', 'post_details'),
)

myblog/myblog/urls.py
from django.conf.urls import patterns, include, url

from blog import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', views.home),
	url(r'^', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

myblog/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey('auth.User')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog.views.post_details', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now=True, editable=False)
    modified_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __unicode__(self):
        return self.body

    def get_absulute_url(self):
        return '/post/%s/' % self.post.pk

myblog/blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

myblog/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Post


class HomeView(ListView):

	template_name = 'index.html'
	queryset = Post.objects.order_by('-created_at')

home = HomeView.as_view()


class PostDetails(DetailView):
	model = Post

post_details = PostDetails.as_view()

myblog/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
    {% include "_post.html" with post=post only %}
    <hr>
	<h4>Comments</h4>
	{% for comment in post.comment_set.all %}
	    <p><em>Posted by {{ comment.name }}</em></p>
	    {{ comment|linebreaks }}
	{% empty %}
	    No comments yet.
	{% endfor %}
{% endblock %}

myblog/templates/_post.html
<article>

    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

    <p class="subheader">
        <time>{{ post.modified_at|date }}</time>
    </p>

    <p></p>

    {{ post.body|linebreaks }}

</article>

myblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Foundation 4</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
</head>
<body>
    <section class="row">
        <header class="large-12 columns">
            <h1>Welcome to My Blog</h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %}{% endblock %}
        </div>

        <div class="large-4 columns">
            <h3>About Me</h3>
            <p>I am a Python developer and I like Django.</p>
        </div>

    </section>

</body>
</html>

myblog/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for post in post_list %}
        {% include "_post.html" with post=post only %}
    {% empty %}
     		<p>No blog post entries yet.</p>
    {% endfor %}
{% endblock content %}